-- 创建数据库
CREATE DATABASE IF NOT EXISTS admin_ai DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE admin_ai;

-- AI模型配置表
CREATE TABLE ai_models (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL COMMENT '模型名称',
  provider VARCHAR(50) NOT NULL COMMENT '服务商：openai, qwen, wenxin, zhipu',
  api_key VARCHAR(255) NOT NULL COMMENT 'API密钥',
  base_url VARCHAR(255) COMMENT 'API基础URL',
  model VARCHAR(100) COMMENT '具体模型名称',
  is_active TINYINT(1) DEFAULT 0 COMMENT '是否启用',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型配置';

-- 知识库表
CREATE TABLE knowledge_base (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '文档标题',
  content TEXT NOT NULL COMMENT 'Markdown内容',
  category VARCHAR(50) COMMENT '分类：guide, faq, api',
  related_routes TEXT COMMENT '关联路由，JSON数组',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库';

-- 路由配置表
CREATE TABLE routes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  path VARCHAR(255) NOT NULL COMMENT '路由路径',
  name VARCHAR(100) NOT NULL COMMENT '页面名称',
  description TEXT COMMENT '页面描述',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_path (path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='路由配置';

-- 对话历史表（可选，MVP阶段可以不存储）
CREATE TABLE chat_history (
  id INT PRIMARY KEY AUTO_INCREMENT,
  session_id VARCHAR(100) NOT NULL COMMENT '会话ID',
  role VARCHAR(20) NOT NULL COMMENT 'user或assistant',
  content TEXT NOT NULL COMMENT '消息内容',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_session (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='对话历史';
